repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/pappasam/toml-sort/
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
        exclude: uv.lock
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.11
    hooks:
      - id: uv-lock
        name: uv-lock shared_code/finmail
        args: [--locked, --offline, --directory, shared_code/finmail]
        files: "^shared_code/finmail/.*"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff check --fix --config pyproject.toml
        files: "^(shared_code|ingest)/.*\\.py$"
      - id: ruff-format
        name: ruff-format
        entry: ruff format --config pyproject.toml
        files: "^(shared_code|ingest)/.*\\.py$"
