repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/pappasam/toml-sort/
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
        exclude: uv.lock
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.5
    hooks:
      - id: uv-lock
        name: uv-lock shared_code/finmail
        args: [--locked, --offline, --directory, shared_code/finmail]
        files: "^shared_code/finmail/.*"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        name: ruff shared_code/finmail
        entry: ruff format --config pyproject.toml
        files: "^shared_code/finmail/.*"
      - id: ruff-format
        name: ruff-format shared_code/finmail
        entry: ruff format --config pyproject.toml
        files: "^shared_code/finmail/.*"
