"""Finmail Configuration Module."""

import json

from pydantic import computed_field, field_validator
from pydantic_settings import BaseSettings

from shared_code.finmail.utils.project import get_version_from_toml


class Settings(BaseSettings):
    """Finmail application settings."""

    # Defaults
    DEFAULT_CATEGORY: str = "Pending Classification"
    DEFAULT_TZ: str = "America/Bogota"

    # Google Sheets
    GOOGLE_SPREADSHEET_IDENTIFIER: str
    GOOGLE_WORKSHEET_NAME: str = "Transactions"
    GOOGLE_CLASSIFICATION_WORKSHEET_NAME: str = "ClassificationRules"

    # Classification
    ENABLE_CLASSIFICATION: bool = True

    # GCP
    GOOGLE_JSON_KEY: dict | str

    # Service
    _service_signature: str = "Autogenerated by Finmail"
    _service_version: str | None = None

    @field_validator("GOOGLE_JSON_KEY", mode="before")
    @classmethod
    def validate_google_json_key(cls, value: dict | None) -> dict | None:  # noqa: D102
        if isinstance(value, str):
            try:
                value = value.replace("\n", "\\n")
                return json.loads(value)
            except json.JSONDecodeError as e:
                raise ValueError(f"GOOGLE_JSON_KEY must be valid JSON: {value}") from e
        return value

    @computed_field  # type: ignore[prop-decorator]
    @property
    def service_version(self) -> str:
        """Get the service version."""
        if self._service_version is not None:
            return self._service_version
        self._service_version = get_version_from_toml()
        return self._service_version

    @computed_field  # type: ignore[prop-decorator]
    @property
    def service_signature(self) -> str:
        """Get the service signature."""
        return f"{self._service_signature} (v{self.service_version})"


settings = Settings()
