"""Finmail Configuration Module."""

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    """Finmail application settings."""

    # Defaults
    DEFAULT_CATEGORY: str = "Pending Classification"
    DEFAULT_TZ: str = "America/Bogota"

    # Service
    SERVICE_SIGNATURE: str = "Autogenerated by Finmail"


settings = Settings()
