"""Finmail Configuration Module."""

from pydantic import computed_field
from pydantic_settings import BaseSettings

from shared_code.finmail.utils.project import get_version_from_toml


class Settings(BaseSettings):
    """Finmail application settings."""

    # Defaults
    DEFAULT_CATEGORY: str = "Pending Classification"
    DEFAULT_TZ: str = "America/Bogota"

    # Service
    _service_signature: str = "Autogenerated by Finmail"
    _service_version: str | None = None

    @computed_field  # type: ignore[prop-decorator]
    @property
    def service_version(self) -> str:
        """Get the service version."""
        if self._service_version is not None:
            return self._service_version
        self._service_version = get_version_from_toml()
        return self._service_version

    @computed_field  # type: ignore[prop-decorator]
    @property
    def service_signature(self) -> str:
        """Get the service signature."""
        return f"{self._service_signature} (v{self.service_version})"


settings = Settings()
